global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

rule_files:
#   - "/var/app/prometheus/alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - '172.17.0.1:9090'
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - '172.17.0.1:9100'
  - job_name: 'nginx-exporter'
    static_configs:
      - targets:
        - '172.17.0.1:9113'
  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://172.17.0.1:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
